version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartjobsearch-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Memory limits to prevent the Free Tier EC2 from crashing
      JAVA_OPTS: "-Xmx300m -Xms300m"
      # These will be passed in from the EC2 instance terminal later
      SPRING_DATASOURCE_URL: ${RDS_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${RDS_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_DB_PASSWORD}
      ML_RECOMMENDER_URL: http://ml-service:5000
    depends_on:
      - ml-service

  ml-service:
    build:
      context: ./ml
      dockerfile: Dockerfile
    container_name: smartjobsearch-ml
    restart: always
    ports:
      - "5000:5000"
